# Generated by Django 3.0.3 on 2020-03-09 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250, verbose_name='Título')),
                ('resumo', models.TextField(verbose_name='Resumo')),
                ('documento', models.FileField(upload_to='arquivos', verbose_name='Documento')),
                ('data_inicio', models.DateTimeField(verbose_name='Data de inicio do Projeto')),
                ('data_fim', models.DateTimeField(verbose_name='Data de Entrega')),
                ('status', models.CharField(choices=[('concluido', 'Concluído'), ('atrasado', 'Atrasado'), ('em_andamento', 'Em Andamento')], max_length=50, verbose_name='Status do Projeto')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('turma', models.CharField(max_length=10, verbose_name='Turma')),
                ('ano', models.CharField(max_length=4, verbose_name='Ano')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetos.Projeto')),
            ],
        ),
    ]
